server:
  port: 8001
  
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.springcloud.test.entities
    mapper-locations:
     - classpath:mybatis/mapper/*.xml

spring:
   application:
    name: microservicecloud-dept
   datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.20.84.119:1433;databaseName=doujltest_20190417
    username: doujltest_20190417
    password: doujltest_20190417
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:  client:    service-url:#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:    instance-id: microservicecloud-dept-8001
    prefer-ip-address: true
   


info:
  app.name: test-microservicecloud
  company.name: www.baidu.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT











